# Generated by Django 4.2.5 on 2023-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyFurryFriend', '0003_emergencycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.AddField(
            model_name='lostpet',
            name='image',
            field=models.ImageField(blank=True, default='path_to_default_image.jpg', null=True, upload_to='lost_pets/'),
        ),
    ]
