# Generated by Django 4.2.5 on 2023-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyFurryFriend', '0004_delete_emergencycontact_lostpet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/'),
        ),
    ]
