# Generated by Django 4.2.5 on 2023-12-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindMyFurryFriend', '0008_alter_lostpet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpet',
            name='species',
            field=models.CharField(max_length=50, verbose_name='Search'),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='species',
            field=models.CharField(max_length=50, verbose_name='Search'),
        ),
    ]
